name: "${name}"
main: "${group}.Pl3xMapMobs"
version: "${version}"
api-version: "1.20"
load: "POSTWORLD"
authors: ${authors}
description: "${description}"
website: "${website}"
softdepend:
  - Pl3xMap
